"""
Django settings for OrderQ project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
_SECRET_KEY_INSECURE_DEFAULT = 'django-insecure-g@l$t7h!hv)__!=&u5_b%)9hkbmmh7qc=d-!_$bda5*bixmkky'
SECRET_KEY = os.environ.get('SECRET_KEY', _SECRET_KEY_INSECURE_DEFAULT)
if not DEBUG and SECRET_KEY == _SECRET_KEY_INSECURE_DEFAULT:
    raise RuntimeError(
        "SECRET_KEY environment variable must be set to a secure value in production (DEBUG=False)."
    )

_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()] or ['localhost', '127.0.0.1', 'backend']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    'orders',
]

# Conditionally add django-celery-beat if available
try:
    import django_celery_beat
    INSTALLED_APPS.append('django_celery_beat')
except ImportError:
    pass

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OrderQ.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OrderQ.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'orderq'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'orders.User'

# Authentication backends — local first, Hive as fallback
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'orders.backends.HiveAuthBackend',
]

# Hive (BSACAIPortal) internal API base URL
HIVE_API_URL = os.environ.get('HIVE_API_URL', 'http://orchestrator-backend:8000')

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/minute',
        # Guest account creation via invite links — tight per-IP cap
        'quick_join': '20/hour',
    },
}

# CSRF settings - Exempt API endpoints from CSRF
# Read from environment variable as comma-separated list, fallback to defaults
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://localhost,https://127.0.0.1')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',') if origin.strip()]

# HTTPS Security Settings
USE_HTTPS = os.environ.get('USE_HTTPS', 'True') == 'True'
if USE_HTTPS:
    # Security settings for HTTPS
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False  # Let nginx handle redirects
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False

CSRF_COOKIE_HTTPONLY = True

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS settings - Read from environment variable or use defaults
cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
else:
    # Default origins (development)
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",
        "https://localhost",
        "http://127.0.0.1:5173",
        "https://127.0.0.1",
    ]

# CORS settings - Allow all origins
CORS_ALLOW_CREDENTIALS = True

# Frontend URL for share messages
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://localhost')

# Hive (BSACAIPortal) SSO — URL of the Hive backend, e.g. https://acai.brightskiesinc.com
HIVE_URL = os.environ.get('HIVE_URL', '')

# Email domains allowed to sign in via SSO (comma-separated). Company-specific
# today; per-tenant configuration once multi-tenancy lands (see docs/BACKLOG.md).
SSO_ALLOWED_EMAIL_DOMAINS = [
    d.strip().lstrip('@')
    for d in os.environ.get('SSO_ALLOWED_EMAIL_DOMAINS', 'brightskiesinc.com').split(',')
    if d.strip()
]

# Cite API base URL
CITE_API_BASE_URL = os.environ.get('CITE_API_BASE_URL', '')

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Schedules defined here are synced into the DatabaseScheduler on beat startup.
from celery.schedules import crontab  # noqa: E402

CELERY_BEAT_SCHEDULE = {
    'enforce-order-cutoffs': {
        'task': 'enforce_order_cutoffs',
        'schedule': 60.0,  # every minute
    },
    'send-payment-reminders': {
        'task': 'send_payment_reminders',
        'schedule': crontab(hour=11, minute=0),  # daily, Africa/Cairo
    },
    'purge-old-records': {
        'task': 'purge_old_records',
        'schedule': crontab(hour=4, minute=0),  # daily retention sweep
    },
    'open-recurring-orders': {
        'task': 'open_recurring_orders',
        'schedule': 60.0,  # every minute
    },
    'auto-close-stale-orders': {
        'task': 'auto_close_stale_orders',
        'schedule': crontab(minute='*/30'),  # sweep twice an hour
    },
}

# Close orders left unfinished (OPEN/LOCKED/ORDERED) this many hours after
# creation — collectors forget to hit Close once the food arrives. Unpaid
# balances remain tracked on the closed order.
AUTO_CLOSE_AFTER_HOURS = int(os.environ.get('AUTO_CLOSE_AFTER_HOURS', 12))

# Retention windows (days) for unbounded tables
NOTIFICATION_RETENTION_DAYS = int(os.environ.get('NOTIFICATION_RETENTION_DAYS', 90))
AUDIT_LOG_RETENTION_DAYS = int(os.environ.get('AUDIT_LOG_RETENTION_DAYS', 365))

# Web Push (VAPID). Generate a key pair once per deployment:
#   npx web-push generate-vapid-keys   (or  python -m py_vapid --gen)
# Leave empty to disable push entirely (in-app + WS notifications still work).
WEBPUSH_VAPID_PUBLIC_KEY = os.environ.get('WEBPUSH_VAPID_PUBLIC_KEY', '')
WEBPUSH_VAPID_PRIVATE_KEY = os.environ.get('WEBPUSH_VAPID_PRIVATE_KEY', '')
WEBPUSH_VAPID_CLAIMS_EMAIL = os.environ.get('WEBPUSH_VAPID_CLAIMS_EMAIL', 'admin@orderq.local')

# Sentry error tracking — no-op unless SENTRY_DSN is set
_sentry_dsn = os.environ.get('SENTRY_DSN', '')
if _sentry_dsn:
    import sentry_sdk
    sentry_sdk.init(
        dsn=_sentry_dsn,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
    )

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '%(asctime)s %(levelname)s %(name)s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'orders': {
            'handlers': ['console'],
            'level': os.environ.get('APP_LOG_LEVEL', 'DEBUG' if DEBUG else 'INFO'),
            'propagate': False,
        },
    },
}

# Channels Configuration
ASGI_APPLICATION = 'OrderQ.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(os.environ.get('REDIS_HOST', 'localhost'), int(os.environ.get('REDIS_PORT', 6379)))],
        },
    },
}
