# Generated by Django 5.2.8 on 2025-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instapay_link',
            field=models.URLField(blank=True, help_text='Instapay payment link for this user', max_length=500),
        ),
    ]
