# Generated by Django 5.2.8 on 2025-11-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_user_instapay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instapay_qr_code',
            field=models.ImageField(blank=True, help_text='QR code image for Instapay', null=True, upload_to='qr_codes/'),
        ),
    ]
