# Generated by Django 5.2.8 on 2025-11-17 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_user_instapay_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionorder',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, help_text='Users assigned to this order (e.g., for birthday cake)', related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='is_private',
            field=models.BooleanField(default=False, help_text='If True, only participants can see this order'),
        ),
        migrations.AlterField(
            model_name='collectionorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.AlterField(
            model_name='collectionorder',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=10),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Recommendation text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='orders.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
