# Generated by Django 5.2.8 on 2026-05-29 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_add_admin_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="feepreset",
            name="fee_split_rule",
            field=models.CharField(
                choices=[
                    ("equal", "Equal"),
                    ("proportional", "Proportional"),
                    ("collector_pays", "Collector Pays"),
                ],
                default="equal",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("locked", "Locked"),
                    ("unlocked", "Unlocked"),
                    ("ordered", "Ordered"),
                    ("closed", "Closed"),
                    ("deleted", "Deleted"),
                    ("item_added", "Item Added"),
                    ("item_removed", "Item Removed"),
                    ("fee_updated", "Fee Updated"),
                    ("user_joined", "User Joined"),
                    ("items_auto_created", "Items Auto-Created"),
                ],
                max_length=20,
            ),
        ),
    ]
