# Generated by Django 5.2.8 on 2026-07-03 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_notification_softdelete_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionorder',
            name='cutoff_processed',
            field=models.BooleanField(default=False, help_text='Whether the cutoff auto-lock has been handled'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='cutoff_reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether the pre-cutoff reminder was sent'),
        ),
        migrations.AddField(
            model_name='collectionorder',
            name='joined_users',
            field=models.ManyToManyField(blank=True, help_text='Users who explicitly joined this order', related_name='joined_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionorder',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('LOCKED', 'Locked'), ('ORDERED', 'Ordered'), ('CLOSED', 'Closed'), ('DELETED', 'Deleted')], db_index=True, default='OPEN', max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='orders_noti_user_id_7da3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_paid', 'user'], name='orders_paym_is_paid_a6b68f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'is_paid'], name='orders_paym_order_i_d10d8c_idx'),
        ),
    ]
