# Generated by Django 5.2.8 on 2026-07-03 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_collectionorder_cutoff_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_status',
            field=models.CharField(choices=[('none', 'No Proof'), ('claimed', 'Proof Uploaded'), ('confirmed', 'Confirmed by Collector'), ('rejected', 'Rejected by Collector')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(unique=True)),
                ('p256dh', models.CharField(max_length=255)),
                ('auth', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
