# Generated by Django 5.2.8 on 2026-07-04 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_payment_proof_image_payment_proof_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.TimeField(help_text='Local time (Africa/Cairo) to open the order')),
                ('weekdays', models.CharField(default='6,0,1,2,3', help_text='Comma-separated weekday numbers, 0=Mon … 6=Sun', max_length=20)),
                ('cutoff_after_minutes', models.PositiveIntegerField(blank=True, help_text='Auto-set cutoff this many minutes after opening', null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_split_rule', models.CharField(choices=[('equal', 'Equal'), ('proportional', 'Proportional'), ('collector_pays', 'Collector Pays')], default='equal', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_orders', to='orders.restaurant')),
            ],
            options={
                'ordering': ['open_at'],
            },
        ),
    ]
