# Generated by Django 5.2.8 on 2026-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_menu_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='previous_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
